{{- if and .Values.authSecret.enabled .Values.authSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitana.authSecretName" . }}
  labels:
    {{- include "gitana.labels" . | nindent 4 }}
  {{- with .Values.authSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  auth.yaml: |-
    username: {{ .Values.authSecret.username | quote }}
    password: {{ .Values.authSecret.password | quote }}
type: Opaque
{{- end }}
