{{- if and .Values.flags.repository.auth.enabled .Values.flags.repository.auth.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitana.authSecretName" . }}
  labels:
    {{- include "gitana.labels" . | nindent 4 }}
  {{- with .Values.flags.repository.auth.secret.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.flags.repository.auth.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  auth.yaml: |-
    username: {{ .Values.flags.repository.auth.username | quote }}
    password: {{ .Values.flags.repository.auth.password | quote }}
type: Opaque
{{- end }}
