apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gitana.fullname" . }}
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - update
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get