apiVersion: v1
kind: Pod
metadata:
  name: gitana
  namespace: gitana
spec:
  containers:
    - args:
        - sync
        - --repository.url=https://github.com/nicolastakashi/poc
        - --repository.path=/tmp/gitana/dashboards
        - --dashboard.labels=grafana_dashboard=true 
        - --dashboard.folder-annotation=dashboard-folder
        - --log.level=info
        - --namespace=gitana
      ports:
        - name: http
          containerPort: 9754
          protocol: TCP
      image: gitana
      imagePullPolicy: IfNotPresent
      name: gitana
      resources:
        limits:
          cpu: "200m"
          memory: 100Mi
        requests:
          cpu: "200m"
          memory: 100Mi
  serviceAccount: gitana