kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitana-rolebind
subjects:
- kind: ServiceAccount
  name: gitana
  namespace: gitana
roleRef:
  kind: Role
  name: gitana-role
  apiGroup: rbac.authorization.k8s.io
